server:
  port: 8080
spring:
  webflux:
    base-path: /${spring.application.name}
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        healthCheckPath: /${spring.application.name}/health
        healthCheckInterval: 15s