server:
  port: 8080
spring:
# google: StripPrefix filter is not able to remove a contextPath if there is any set
#  webflux:
#    base-path: /${spring.application.name}
  application:
    name: gateway
  rabbitmq:
    addresses: localhost:5672
    username: root
    password: 123456
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        healthCheckPath: /health
#        healthCheckPath: /${spring.application.name}/health
        healthCheckInterval: 15s
    function:
      definition: route
    stream:
      bindings:
        route-in-0:
          destination: route-topic
        route-out-0:
          destination: route-topic