server:
  port: 8083
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: auth
  rabbitmq:
    addresses: localhost:5672
    username: root
    password: 123456
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.value}
        healthCheckPath: /${spring.application.name}/health
        healthCheckInterval: 15s
    stream:
      bindings:
        route-in-0:
          destination: route-topic
        route-out-0:
          destination: route-topic